### ISSUE TITLE
Java compatibility for Android

### ISSUE THREAD

**Issue by mcqueary** [nats-io/java-nats#24]
Currently Android Studio only supports Java 7, and many Android devices are still stuck with Java 6 runtime environment. To support running in these older environments, it would be ideal if the jnats implementation could retain Java 6 runtime compatibility.

**Comment by remotegun** [comment]
to avoid crashing cause by current jnats, I have to set the minimum Android SDK version to 18. but it turned number of supported devices from more than 10,000 to almost 6,000.

**Comment by remotegun** [comment]
Due to a documented error, using jnats on older devices cause this error:

java.lang.NoClassDefFoundError: java.util.concurrent.Phaser
                                                                              at io.nats.client.ConnectionImpl.<init>(ConnectionImpl.java:156)
                                                                              at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:257)
                                                                              at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:249)

**Comment by pires** [comment]
As a side note, [Java 8 is supported on Android N](https://developer.android.com/preview/j8-jack.html).

**Comment by remotegun** [comment]
@pires yes, but it is SDK 23. there are more than 4,000 devices which doesn't support even SDK 18.

**Comment by pires** [comment]
@remotegun I didn't nor do disagree. It was just a side note for (who knows?) future reference.

**Comment by mcqueary** [comment]
@remotegun  @pires 

I have changed the NATS parent pom to default to java 1.7, and made the necessary code changes for now. I'm extremely reluctant to drop back to Java 6. Farzad can you please test this?

If needed, I can get rid of the Phaser usage, which was only experimental to begin with.

**Comment by remotegun** [comment]
@mcqueary the current pom.xml isn't changed recently. were should I get the new version you were working on it?

**Comment by mcqueary** [comment]
The change is in the [nats-parent-pom](https://github.com/nats-io/nats-parent-pom).

**Comment by remotegun** [comment]
mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: osx-x86_64
[WARNING] Failed to inject repository session properties.
java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/eclipse/aether/RepositorySystemSession;
	at kr.motd.maven.os.RepositorySessionInjector.injectRepositorySession(RepositorySessionInjector.java:22)
	at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:148)
	at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:107)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building NATS Parent POM 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @ nats-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (default-prepare-agent) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (pre-unit-test) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:report (post-unit-test) @ nats-parent ---
[INFO] Skipping JaCoCo execution due to missing execution data file:/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.3:jar (attach-javadocs) @ nats-parent ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ nats-parent >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @ nats-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (default-prepare-agent) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (pre-unit-test) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ nats-parent <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ nats-parent ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.847s
[INFO] Finished at: Sat Jun 25 20:24:44 IRDT 2016
[INFO] Final Memory: 14M/81M
[INFO] ------------------------------------------------------------------------

**Comment by mcqueary** [comment]
You need to `mvn install` and then build jnats.

**Comment by aricart** [comment]
What specific Android versions are you targeting?

**Comment by remotegun** [comment]
INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: osx-x86_64
[WARNING] Failed to inject repository session properties.
java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/eclipse/aether/RepositorySystemSession;
	at kr.motd.maven.os.RepositorySessionInjector.injectRepositorySession(RepositorySessionInjector.java:22)
	at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:148)
	at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:107)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building NATS Parent POM 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @ nats-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (default-prepare-agent) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (pre-unit-test) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:report (post-unit-test) @ nats-parent ---
[INFO] Skipping JaCoCo execution due to missing execution data file:/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.3:jar (attach-javadocs) @ nats-parent ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ nats-parent >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-default) @ nats-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ nats-parent ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (default-prepare-agent) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (pre-unit-test) @ nats-parent ---
[INFO] surefireArgLine set to -javaagent:/Users/Farzad/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/Farzad/Downloads/nats-parent-pom-master/target/coverage-reports/jacoco-ut.exec
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ nats-parent <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ nats-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ nats-parent ---
[INFO] Installing /Users/Farzad/Downloads/nats-parent-pom-master/pom.xml to /Users/Farzad/.m2/repository/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.356s
[INFO] Finished at: Mon Aug 01 17:59:08
[INFO] Final Memory: 14M/81M
[INFO] ------------------------------------------------------------------------

**Comment by remotegun** [comment]
do you have any hints for me to fix it?

**Comment by aricart** [comment]
@remotegun  I have created a branch https://github.com/nats-io/jnats/tree/long-exception you can try with your client. The parsing code was throwing the NumberFormatExceptions, and killing your client. The branch will initiate a reconnect. Let me know if this solves the issue on your side.

**Comment by mcqueary** [comment]
Closed by #55

**Comment by remotegun** [comment]
Yes, it’s working from android >= 18

**Comment by KORuL** [comment]
@remotegun I try it yesterday, but get this error


```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
    at io.nats.client.Options.<clinit>(Options.java:80)
    at io.nats.client.Options$Builder.<init>(Options.java:390)
    at com.example.aniketbapat.demoapp.MainActivity$ConnectServer.doInBackground(MainActivity.java:70)
    at com.example.aniketbapat.demoapp.MainActivity$ConnectServer.doInBackground(MainActivity.java:60)
    at android.os.AsyncTask$2.call(AsyncTask.java:304)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
    at java.lang.Thread.run(Thread.java:762)`
```

**Comment by remotegun** [comment]
try this version and let me know the result:
compile 'io.nats:jnats:0.7.3'

**Comment by KORuL** [comment]
implementation 'io.nats:jnats:1.0' work fine with gnatsd Release v1.3.0 on android > 18
Thanks a lot!
I create Issue for others people #198

**Comment by remotegun** [comment]
Good to hear that.

Good luck
